---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          cache-dependency-glob: pyproject.toml
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files
        env:
          SKIP: no-commit-to-branch

      - name: Build LaTeX PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./paper/latex/
